apiVersion: v1
kind: Service
metadata:
  name: devops-demo-api
  labels:
    app: devops-demo-api
spec:
  selector:
    app: devops-demo-api
  ports:
    - name: http          # name matters: ServiceMonitor targets it by name
      port: 80
      targetPort: 8000
